### ISSUE TITLE
 Inoreader  的弹窗能屏蔽吗  老是弹出来。

### ISSUE THREAD

**Issue by wq587040** [BennyThink/KeepABPOn#1]
检测到 Adblock 插件！
广告对于维持 @ Inoreader 的运行有实实在在的帮助。所以请支持我们，把我们的域名添加到您的广告过滤程序白名单。 除了浏览器的广告过滤扩展，您可能还要将我们的域名添加到 VPN 或者杀毒软件的广告过滤白名单中。 操作完成后，请刷新本页面 您还可以升级到我们的入门套餐来移除广告。
升级套餐，获得无广告体验
现在不想（下次再说）

**Comment by BennyThink** [comment]
可是我并没有在inoreader的页面上看到广告唉😔

**Comment by wq587040** [comment]
> 可是我并没有在inoreader的页面上看到广告唉

刚刚我已经解决了
